#!/usr/bin/env python3
"""
API Key Leak Scanner v2.1 — Scans GitHub for exposed API keys in AI-generated projects.
Opimized for rate limits, with backtracking retries and proper JSON output.
"""

import json, re, os, sys, time, base64, ssl, traceback
import urllib.request, urllib.error, urllib.parse
from datetime import datetime, timezone, timedelta
from collections import Counter
from pathlib import Path

# ─── Configuration ─────────────────────────────────────────────────────
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
SCAN_DURATION   = int(os.environ.get("SCAN_DURATION", "45"))
RATE_LIMIT      = int(os.environ.get("RATE_LIMIT", "10"))   # req/min (code search)
PAUSE           = max(0.1, 60.0 / float(RATE_LIMIT))       # seconds between requests
OUTPUT_DIR      = os.path.expandvars(
                      os.environ.get("OUTPUT_DIR",
                          os.path.expanduser("~/.hermes/data/key-scanner"))
                  )

# ─── Key Patterns ──────────────────────────────────────────────────────
KEY_PATTERNS = [
    ("OpenAI API",           r'(?:sk-proj-|sk-)[a-zA-Z0-9]{20,}(?:[A-Za-z0-9_-]{20,})?'),
    ("Anthropic API",        r'sk-ant-[a-zA-Z0-9]{20,}'),
    ("Google/Gemini",        r'AIza[0-9A-Za-z\-_]{35}'),
    ("GitHub PAT",           r'ghp_[a-zA-Z0-9]{36}'),
    ("GitHub OAuth",         r'(?:gho_|ghu_|ghs_|ghr_)[a-zA-Z0-9]{36}'),
    ("Stripe Live",          r'sk_live_[a-zA-Z0-9]{24,}'),
    ("Stripe Test",          r'sk_test_[a-zA-Z0-9]{24,}'),
    ("AWS Access Key",       r'AKIA[0-9A-Z]{16}'),
    ("Azure Key",            r'(?i)azure.{0,20}(?:api|subscription|openai)_?key["\']?\s*[:=]\s*["\']([a-zA-Z0-9_\-]{32,})["\']'),
    ("Slack Bot Token",      r'xox[baprs]-[0-9a-zA-Z\-]{10,}'),
    ("Slack Webhook",        r'https://hooks\.slack\.com/services/[A-Za-z0-9/]{40,}'),
    ("Discord Bot Token",    r'[MN][A-Za-z\d]{23}\.[A-Za-z\d]{6}\.[A-Za-z\d\-_]{27}'),
    ("Telegram Bot Token",   r'[0-9]{8,10}:[a-zA-Z0-9_-]{35}'),
    ("xAI/Grok API",         r'(?:xai|grok)[_-][a-zA-Z0-9]{20,}'),
    ("DeepSeek API",         r'(?:deepseek|ds)[_-][a-zA-Z0-9]{20,}'),
    ("JWT/Bearer",           r'eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}'),
    ("Generic API Key",      r'(?i)(?:api_key|apisecret|api_secret|secret_key|private_key)\s*[=:]\s*["\']([a-zA-Z0-9_\-@#$%^&+=]{16,})["\']'),
    ("AWS Secret",           r'(?i)(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY)\s*[=:]\s*"?([a-zA-Z0-9/+]{40})"?'),
    ("Google OAuth",         r'[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com'),
]

AI_INDICATORS = [
    "generated by ai", "generated by chatgpt", "generated by claude",
    "generated by copilot", "built with chatgpt", "built with claude",
    "created with ai", "created with chatgpt", "made with ai",
    "ai generated", "ai-generated", "chatgpt generated", "claude generated",
    "i asked chatgpt", "i asked claude", "no coding experience",
    "first time coding", "beginner project", "learning to code",
    "ai assisted", "ai-assisted", "using chatgpt to", "using claude to",
    "generated by artificial intelligence", "built with artificial intelligence",
    "von ki generiert", "mit ki erstellt", "ki-generiert",
    "auto-generated", "autogenerated", "auto generated",
    "prompt engineering project", "created entirely by ai",
]

SUSPICIOUS_FILES = [
    ".env", ".env.example", ".env.local", ".env.development", ".env.production",
    "config.json", "config.yaml", "config.yml", "secrets.json", "secrets.yaml",
    "credentials.json", "credentials.yml", "appsettings.json", "settings.json",
    "docker-compose.yml", "docker-compose.yaml", "firebase-config.json",
    "service-account.json", "serviceAccountKey.json", "application.yml",
    ".env.test", "env.yaml", "env.json",
]

SKIP_VALUES = [
    "your-api-key", "your_key", "xxxxx", "example", "changeme", "change_me",
    "your_", "replace_with", "placeholder", "sk-your", "sk-xxxxxxxx",
    "api_key_here", "your_token_here", "sk-proj-your", "put_your", "replace_me",
    "insert_", "todo", "sample_", "----", "======",
]

# ─── Retry / Rate-Limit Helpers ─────────────────────────────────────────
_CLOCK = time.monotonic
_CTX   = ssl.create_default_context()

def _github(url, retries=3):
    """GET GitHub API, retry on 403 with exponential backoff."""
    waited = set()
    for attempt in range(retries):
        req = urllib.request.Request(url)
        req.add_header("User-Agent", "HermesKeyScout/2.1")
        req.add_header("Accept", "application/vnd.github.v3+json")
        if GITHUB_TOKEN:
            req.add_header("Authorization", f"Bearer {GITHUB_TOKEN}")
        try:
            resp = urllib.request.urlopen(req, timeout=20, context=_CTX)
            return json.loads(resp.read()), resp.status
        except urllib.error.HTTPError as e:
            if e.code == 403:
                now = time.time()
                reset = getattr(e, "headers", {}).get("X-RateLimit-Reset")
                if reset:
                    wait = max(float(reset) - now, 0)
                else:
                    wait = 60 * (attempt + 1)
                if wait < 300:
                    sys.stderr.write(f"  [!] 403 — sleeping {wait:.0f}s\n")
                    time.sleep(wait + 1)
                    continue
                return None, 403
            return None, e.code
        except (urllib.error.URLError, TimeoutError):
            time.sleep(PROGRESSIVE_BACKOFF(attempt))
    return None, 0


def PROGRESSIVE_BACKOFF(attempt):
    return min(30, 2 ** attempt)

def is_ai_text(text):
    if not text: return False
    return any(k in text.lower() for k in AI_INDICATORS)

def is_skip(val):
    return any(k in val.lower() for k in SKIP_VALUES)

def validate(val, ktype):
    if is_skip(val): return False
    if len(val) < 15: return False
    return True

def fetch_content(repo, path):
    safe = urllib.parse.quote(path)
    data, _ = _github(f"https://api.github.com/repos/{repo}/contents/{safe}")
    if data and isinstance(data, dict) and "content" in data:
        try:
            c = data["content"].replace("\n", "").replace(" ", "")
            return base64.b64decode(c).decode("utf-8", errors="replace")
        except Exception:
            pass
    return None

def scan_key_hits(content, file_path, repo, url):
    hits = []
    for ktype, pat in KEY_PATTERNS:
        for m in re.finditer(pat, content):
            val = m.group(0) if not m.groups() else m.group(1)
            if not validate(val, ktype):
                continue
            preview = val[:15] + "..." + val[-5:] if len(val) > 22 else val[:16] + "..."
            hits.append({"type": ktype, "preview": preview,
                         "length": len(val), "file": file_path,
                         "repo": repo, "url": f"{url}/blob/main/{file_path}"})
    return hits

# ─── Main Scanner ───────────────────────────────────────────────────────
class Scanner:
    def __init__(self):
        self.findings, self.repos, self.files, self.api = [], 0, 0, 0
        self.start = time.monotonic()
        self.deadline = self.start + SCAN_DURATION * 60
        self.seen = set()

    @property
    def expired(self): return time.monotonic() >= self.deadline

    def add(self, hits, repo=None):
        for h in hits:
            key = f"{h['type']}|{h['preview']}|{h.get('repo','?')}"
            if key not in self.seen:
                self.seen.add(key)
                self.findings.append(h)

    def repos_scan(self, query, pages=3):
        for page in range(1, pages + 1):
            if self.expired: return
            url = (f"https://api.github.com/search/repositories?"
                   f"q={urllib.parse.quote(query)}&sort=updated&per_page=30&page={page}")
            data, _ = _github(url); self.api += 1
            if not data: break
            for r in data.get("items", []):
                if self.expired: return
                self.repos += 1
                fname = r["full_name"]
                desc  = r.get("description", "") or ""
                readme = ""
                rd, _ = _github(f"https://api.github.com/repos/{fname}/readme"); self.api += 1
                if rd and isinstance(rd, dict) and "content" in rd:
                    try:
                        c = rd["content"].replace("\n", "").replace(" ", "")
                        readme = base64.b64decode(c).decode("utf-8", errors="replace")
                    except: pass
                if is_ai_text(desc) or is_ai_text(readme):
                    sys.stderr.write(f"  → {fname}\n")
                    self.repo_root_scan(fname, r["html_url"])

    def repo_root_scan(self, repo, url):
        """Fetch root dir list + scan suspicious files + common subdirs."""
        data, _ = _github(f"https://api.github.com/repos/{repo}/contents/"); self.api += 1
        if not data or not isinstance(data, list): return

        # ── Root files ──────────────────────────────────────────────────
        for item in data:
            if self.expired: return
            if item["type"] != "file": continue
            name = item["name"].lower()
            if not any(k in name for k in ["env","config","secret","key","token","cred","auth","passwd"]
                       ) and not any(name.endswith(s) for s in [
                           ".env", ".yaml", ".yml", ".json", ".properties"
                       ]): continue
            c = fetch_content(repo, item["path"])
            if c:
                self.files += 1
                self.add(scan_key_hits(c, item["path"], repo, url))
            time.sleep(PAUSE)

        # ── Subdir scan ────────────────────────────────────────────────
        for item in data:
            if self.expired: return
            if item["type"] != "dir": continue
            if item["name"] not in {"src","backend","app","config","bot",
                                    "scripts","api","server","lib","utils"}: continue
            d, _ = _github(f"https://api.github.com/repos/{repo}/contents/{item['name']}"); self.api += 1
            if not d or not isinstance(d, list): continue
            for si in d:
                if self.expired: return
                if si["type"] != "file": continue
                sn = si["name"].lower()
                if not any(k in sn for k in ["env","config","secret","key","token","cred"]): continue
                c = fetch_content(repo, si["path"])
                if c:
                    self.files += 1
                    self.add(scan_key_hits(c, si["path"], repo, url))
                time.sleep(PAUSE * 0.7)

    def code_search(self, q, max_page=3):
        for page in range(1, max_page + 1):
            if self.expired: return
            url = (f"https://api.github.com/search/code?"
                   f"q={urllib.parse.quote(q)}&per_page=25&page={page}")
            data, _ = _github(url); self.api += 1
            if not data: return
            for it in data.get("items", []):
                if self.expired: return
                r    = it.get("repository", {})
                rn   = r.get("full_name", "")
                fp   = it.get("path", "")
                ru   = r.get("html_url", "")
                c    = fetch_content(rn, fp)
                if c:
                    self.files += 1
                    self.add(scan_key_hits(c, fp, rn, ru),
                             repo=f"{rn} | path:{fp}")
                    if self.findings:
                        sys.stderr.write(f"  >> LEAK in {rn}/{fp}\n")
                time.sleep(PAUSE)



# ─── Balance Checking ─────────────────────────────────────────────────────
def check_openai_balance(key):
    try:
        req = urllib.request.Request("https://api.openai.com/v1/dashboard/billing/credit_grants")
        req.add_header("Authorization", f"Bearer {key}")
        req.add_header("Content-Type", "application/json")
        resp = urllib.request.urlopen(req, timeout=8, context=ssl.create_default_context())
        d = json.loads(resp.read())
        total = d.get("total_granted", 0)
        used = d.get("total_used", 0)
        rem = total - used
        return f"${rem:.2f} remaining (of ${total:.2f})" if total else "no grants"
    except urllib.error.HTTPError as e:
        return "INVALID" if e.code == 401 else f"HTTP {e.code}"
    except Exception:
        return "check failed"

def check_github_pat(key):
    try:
        req = urllib.request.Request("https://api.github.com/user")
        req.add_header("Authorization", f"Bearer {key}")
        req.add_header("User-Agent", "HermesKeyScout/2.1")
        resp = urllib.request.urlopen(req, timeout=8, context=ssl.create_default_context())
        d = json.loads(resp.read())
        name = d.get("name") or d.get("login", "?")
        return f"valid — {name}"
    except urllib.error.HTTPError as e:
        return "INVALID" if e.code == 401 else f"HTTP {e.code}"
    except Exception:
        return "check failed"

def check_stripe_balance(key):
    try:
        auth = base64.b64encode(f"{key}:".encode()).decode()
        req = urllib.request.Request("https://api.stripe.com/v1/balance")
        req.add_header("Authorization", f"Basic {auth}")
        resp = urllib.request.urlopen(req, timeout=8, context=ssl.create_default_context())
        d = json.loads(resp.read())
        available = sum(a.get("amount",0)/100 for a in d.get("available",[]))
        pending = sum(a.get("amount",0)/100 for a in d.get("pending",[]))
        return f"avail: ${available:.2f} | pending: ${pending:.2f}"
    except urllib.error.HTTPError as e:
        return "INVALID" if e.code == 401 else f"HTTP {e.code}"
    except Exception:
        return "check failed"

BALANCE_CHECKERS = {
    "OpenAI API": check_openai_balance,
    "GitHub PAT": check_github_pat,
    "Stripe Live": check_stripe_balance,
}


# ─── Report ─────────────────────────────────────────────────────────────
def report(scanner):
    elapsed = time.monotonic() - scanner.start
    dur     = f"{int(elapsed//60)}m {int(elapsed%60)}s"
    status  = "TIME LIMIT REACHED" if scanner.expired else "ALL PHASES DONE"

    def box(title):    return f"╔{'═'*64}╗\n║{title:^64}║\n╠{'═'*64}╣"
    def line(k,v):     return f"║  {k:<20}  {str(v):<42}║"
    def sep():         return "╠" + "═"*64 + "╣"
    def finish():      return "╚" + "═"*64 + "╝"

    rows = []
    rows.append(box("  API Key Leak Scan Report  "))
    rows.append(line("Date", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")))
    rows.append(line("Duration", dur))
    rows.append(line("Repos scanned", scanner.repos))
    rows.append(line("Files inspected", scanner.files))
    rows.append(line("API calls (cached)", scanner.api))
    rows.append(line("Auth", "Yes" if GITHUB_TOKEN else "No"))

    if not scanner.findings:
        rows.append(sep())
        rows.append("║  KAUM ÜBEREINSTIMMUNGEN — keine Keys gefunden              ║")
        rows.append(finish())
        return "\n".join(rows), scanner.findings

    rows.append(sep())
    rows.append(f"║  🔑 LEAKS GEFUNDEN: {len(scanner.findings)}                                  ║")
    rows.append(sep())
    rows.append(f"║  {'Typ':<16} │ {'Preview':<18} │ {'Guthaben/Status':<20} │ {'Repository':<18}║")
    rows.append(f"║  {'─'*16}┼{'─'*18}┼{'─'*20}┼{'─'*18}║")
    for f in scanner.findings[:20]:
        r = f["repo"][:20] + "..." if len(f["repo"]) > 20 else f["repo"]
        # ── Guthaben/Status check ──
        bal = "N/A"
        ktype = f["type"]
        if ktype in BALANCE_CHECKERS:
            bal = "check..."
        rows.append(f"║  {f['type']:<16} │ {f['preview']:<18} │ {bal:<20} │ {r:<18}║")
    if len(scanner.findings) > 20:
        rows.append(f"║  ... +{len(scanner.findings)-20} mehr                               ║")

    rows.append(sep())
    rows.append("║  NACH TYP                                                   ║")
    rows.append(sep())
    for t,n in Counter(f["type"] for f in scanner.findings).most_common(10):
        rows.append(f"║  ● {t:<27} {n}                  ║")

    rows.append(sep())
    rows.append("║  TOP-AI-GENERIERTE REPOS (Preview)                         ║")
    rows.append(sep())
    rc = Counter(f["repo"] for f in scanner.findings)
    for r,n in rc.most_common(8):
        rows.append(f"║  • {r[:45]:<45} {n}              ║")

    rows.append(sep())
    rows.append(f"║   Status: {status:<49}║")
    rows.append(finish())
    return "\n".join(rows), scanner.findings

# ─── Main ────────────────────────────────────────────────────────────────
def main():
    sys.stderr.write("="*65 + "\n  API Key Leak Scanner v2.1\n  Start: " +
                     datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC") + "\n" +
                     f"  Dauer: {SCAN_DURATION}min | Auth: {'Ja' if GITHUB_TOKEN else 'Nein'}\n" + "="*65 + "\n\n")

    s = Scanner()
    t0 = s.start

    sys.stderr.write("[Phase 1/3] AI-generated Repos durchsuchen...\n")
    for q in [ "generated+by+chatgpt+in:readme", "ai-generated+in:readme",
               "built+with+claude+in:readme", "created+with+ai+in:readme",
               "auto-generated+in:readme", "generated+by+artificial+intelligence+in:readme" ]:
        s.repos_scan(q, pages=3)
        if s.expired: break
        time.sleep(PAUSE)

    if not s.expired:
        sys.stderr.write("\n[Phase 2/3] Direktsuche nach Keys in Config-Dateien...\n")
        for q in [ "OPENAI_API_KEY+path:.env", "ANTHROPIC_API_KEY+path:.env",
                   "sk-proj-+path:.env",  "SKANT_API_KEY+path:.env",
                   "path:.env+API_KEY", "sk_live_+path:.env",
                   "ghp_+path:.env", "TOKEN+path:.env+language:env" ]:
            s.code_search(q, max_page=2)
            if s.expired: break

    if not s.expired:
        sys.stderr.write("\n[Phase 3/3] Gists...\n")
        for q in ["API_KEY+language:env", "sk-proj-+language:json", "SECRET_KEY+language:yaml"]:
            s.code_search(q, max_page=2)
            if s.expired: break

    out, findings = report(s)
    print(out)

    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    ts   = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    path = os.path.join(OUTPUT_DIR, f"scan_{ts}.json")
    json.dump({
        "scan_time": datetime.now(timezone.utc).isoformat(),
        "duration_s": int(time.monotonic() - t0),
        "repos_scanned": s.repos,
        "files_inspected": s.files,
        "api_calls": s.api,
        "findings": findings,
    }, open(path,"w"), indent=2)
    sys.stderr.write(f"\n[📁] JSON: {path}\n")
    print(f"\n[📁] Detailed JSON: {path}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[!] Scan abgebrochen.")
        sys.exit(1)
    except Exception as e:
        print(f"\n[!!] Fehler: {e}")
        traceback.print_exc()
        sys.exit(1)
